### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by bruno-oliveira1** [Fer99n/spotify-to-deezer#1]
First of all thanks for your work, didn't find your email so I'm opened this issue, because I've a playlist with 2k songs but the script only import 100 to deezer this is a limitation or I'm doing something wrong ?

**Comment by nocfer** [comment]
Hi! Thanks for your appreciations, it seems that spotify APIs limits the returned tracks to 100, I will adapt the code as soon as possible to make it work with playlists of every length.

**Comment by bruno-oliveira1** [comment]
Thanks for quick answering, I was trying to figure out and I found exactly the same you told me. On spotify's API reference
https://developer.spotify.com/documentation/web-api/reference/#category-playlists, a found two variables limit, The maximum number of items to return. Default: 100. Minimum: 1. Maximum: 100, offset The index of the first item to return. Default: 0 (the first object)., so if you do a loop changing the offset value adding 100 to get the next 100 tracks and concatenate the results it's a way of doing I would like to help but I have any knowledge of python :(.

**Comment by partoftheworlD** [comment]
These values are not needed, after requesting https://api.spotify.com/v1/playlists/{playlist_id} the response will return a link to the next page: 
response.json()['tracks']['next'] -> https://api.spotify.com/v1/playlists/{playlist_id}/tracks?offset=100&limit=100
or just make request to
https://api.spotify.com/v1/playlists/{playlist_id}?fields=tracks(next) you will get the same result
Example here:  https://github.com/partoftheworlD/Spotty2Deezer

**Comment by nocfer** [comment]
Thanks for your suggestions guys, I already have the solution to this, I'll update the repo asap

**Comment by nocfer** [comment]
I'm sorry for the wait guys, I pushed an update to the repo that should fix the issue. Let me know if I messed up something
